### ISSUE TITLE
Auto-Detect Installation Path

### ISSUE THREAD

**Issue by sprankhub** [Atwix/phpstorm-plugin-feedback#1]
It is tedious having to set the Magento installation path manually. It would be much nicer if this was auto-detected. E.g., automatically check if Magento is installed inside the project directory or also one directory level further down. Maybe you can pre-fill the setting if the path can be auto-detected in one of these directories?

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub !

We have developed auto-detection for the **Installation Path** field.

How it works:

On project startup plugin checks if plugin is disabled **or** if installation path is empty.
If so, next notification is shown for user:

<img width="900" alt="Screenshot 2022-12-21 at 20 35 29" src="https://user-images.githubusercontent.com/31848341/209204044-e75bef4f-b95f-4c4f-b94d-face2ccd3609.png">

If user choses **Yes**:

- is enabled switches to **yes**
- installation path is auto-populated
- reindex is run

Those changes will be available in the next release.

Regards,
