### ISSUE TITLE
Compare Preference With Original Class

### ISSUE THREAD

**Issue by sprankhub** [Atwix/phpstorm-plugin-feedback#12]
This is a follow-up of https://github.com/Atwix/phpstorm-plugin-feedback/issues/4#issuecomment-1441319948.

If I am looking at a preference, I often want to compare the class with the overridden class. So it would also be nice to have a feature "Compare class with parent" or "Compare preference with original class" or something alike.

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub!

Thank you!

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub!

This feature is implemented in the 2023.3.0 version of the plugin.
I am closing this task as resolved.

Regards,
