### ISSUE TITLE
[New feature] Add ability to view a layouts for the selected template

### ISSUE THREAD

**Issue by SilinMykola** [Atwix/phpstorm-plugin-feedback#13]
Hello! I get the idea to add a feature to see in what layouts we use the selected template. We can click on the name of the template, or the open tab with the template. What do you think?
![image](https://user-images.githubusercontent.com/15772032/221178619-c97e965f-a3a1-4948-9588-bcaab5458feb.png)

**Comment by bohdan-harniuk** [comment]
Hello, @SilinMykola!

This feature is implemented in the 2023.3.0 version of the plugin.
I am closing this task as resolved.

Regards,
