### ISSUE TITLE
Add possibility to compare overridden JS files with the original one

### ISSUE THREAD

**Issue by norgeindian** [Atwix/phpstorm-plugin-feedback#15]
In my eyes, it would be awesome to have the "Compare overridden template with original one" functionality, which already exists for `.phtml` templates, also for JS files.

**Comment by bohdan-harniuk** [comment]
Hello, @norgeindian!
This is implemented in the 2023.2 version of the plugin. Please, update your plugin and try it out.
Regards,

**Comment by bohdan-harniuk** [comment]
@norgeindian, feel free to request more features.
I am closing this issue as It is already implemented.

Regards,

**Comment by norgeindian** [comment]
@bohdan-harniuk , thanks a lot and sorry for not checking, that I'm on the latest version. Just updated and indeed, this works perfectly. Thanks.
