### ISSUE TITLE
Add possibility to compare overridden html files with the original one

### ISSUE THREAD

**Issue by norgeindian** [Atwix/phpstorm-plugin-feedback#16]
In my eyes, it would be awesome to have the "Compare overridden template with original one" functionality, which already exists for `.phtml` templates, also for `html` files.

**Comment by bohdan-harniuk** [comment]
Hello, @norgeindian!
This is implemented in the 2023.2 version of the plugin. Please, update your plugin and try it out.
Regards,

**Comment by bohdan-harniuk** [comment]
@norgeindian, feel free to request more features.
I am closing this issue as It is already implemented.

Regards,
