### ISSUE TITLE
Bug ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SilinMykola** [Atwix/phpstorm-plugin-feedback#22]
![image](https://user-images.githubusercontent.com/15772032/232438667-eb71c644-e0a1-4b9d-b9de-39dc842ed3d2.png)

**Comment by bohdan-harniuk** [comment]
Hello, @SilinMykola!

This bug is fixed. Fix will be available in the upcoming release.

Regards,

**Comment by bohdan-harniuk** [comment]
Hi @SilinMykola, 

New release 2023.4 is publicly available. I am closing this issue as solved.

Regards,
