### ISSUE TITLE
Compare templates feature supporting hyva compatibility modules

### ISSUE THREAD

**Issue by norgeindian** [Atwix/phpstorm-plugin-feedback#30]
To reproduce the issue, you need to have the following setup:

- custom theme based on Hyva
- third party module
- Hyva compatibility module for the third party module
- override of a template based on the hyva compatibility module in your theme

If you now open the overridden template and use the "compare overridden file with source" functionality, your template is falsely compared to the original template from the third party module, not the one from the hyva compatibility module.
It would be awesome, if the override could be directly compared to the template from the compatibility module.

**Comment by bohdan-harniuk** [comment]
Hello, @norgeindian!

Thank you, we will implement it in the upcoming release.

**Comment by bohdan-harniuk** [comment]
Hi, @norgeindian!

This feature is already implemented in the latest release: 2023.5.0. I am closing this task as completed. Please, share your ideas with us so we can implement more useful things in the next releases.

Regards,

**Comment by norgeindian** [comment]
@bohdan-harniuk , thanks a lot. Awesome. Just tested it, works fine. Thanks
