### ISSUE TITLE
Quick Fix To Add Missing @vars To E-Mail Templates

### ISSUE THREAD

**Issue by sprankhub** [Atwix/phpstorm-plugin-feedback#31]
`phpcs` might sometimes report things like this:

     1 | WARNING | Template @vars comment block is missing a variable
       |         | used in the template.
       |         | Missing variable: var some_var_ame

If this applies to many variables, it is tedious to fix it. It would be nice to have a quick-fix, which inserts the variables into the e-mail template. References / examples:

* https://github.com/magento/magento-coding-standard/blob/aec6744c0d1ad05f836b653e43dde756f23a389d/Magento2/Sniffs/Html/HtmlDirectiveSniff.php#L251-L259
* https://github.com/magento/magento2/blob/d9d3d9b40bfdc683ac7c6a26b605481a25e3493e/app/code/Magento/Sales/view/frontend/email/order_new.html#L8-L27

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub!

Great idea, we will consider adding it to near releases.

Thank you,

**Comment by bohdan-harniuk** [comment]
Hi, @sprankhub!

This feature is already implemented in the latest release: 2023.5.0. I am closing this task as completed. Please, share your ideas with us so we can implement more useful things in the next releases.

Regards,
