### ISSUE TITLE
[BUG] - The Magento version in the project is not upgraded if you previously had a different one.

### ISSUE THREAD

**Issue by Mr-Leonerrr** [Atwix/phpstorm-plugin-feedback#32]
## Description
When you have an initial version of Magento in the project and you have the extension configured, the version is correct. After making an upgrade to the Magento version, the change is not reflected when you select the project path again.

### Initial version (2.4.3-p1)
![image](https://github.com/Atwix/phpstorm-plugin-feedback/assets/56647065/ce646ca6-bd90-49a2-a0e3-62572c479877)

### Current Version (2.4.6-p1)
![image](https://github.com/Atwix/phpstorm-plugin-feedback/assets/56647065/e96c67a9-bed5-49ea-8ca0-15b7b7aa70c7)

### System Information
PhpStorm 2023.1.3
Build #PS-231.9161.47, built on June 21, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1970M
Cores: 6
Plugin version: 2023.5.0

**Comment by bohdan-harniuk** [comment]
Hello, @Mr-Leonerrr!

Thank you for your report.

**Comment by bohdan-harniuk** [comment]
Hi @Mr-Leonerrr,

We have fixed this issue. In the next release, two options will be available:

- manually refresh Magento version on demand
- automatically update Magento version on project startup

I will update this task to inform you once these updates are released.

Regards,

**Comment by bohdan-harniuk** [comment]
Hi @Mr-Leonerrr ,

We've released mentioned changes. Please, update your plugin to the latest available.

Regards,
