### ISSUE TITLE
Template @vars comment block contains invalid JSON to E-Mail Templates

### ISSUE THREAD

**Issue by RanaMuhammadIrshad** [Atwix/phpstorm-plugin-feedback#33]
As adding multiple missing @vars to E-Mail Templates is fixed in the issue #31.

https://github.com/Atwix/phpstorm-plugin-feedback/issues/31

However, if there are more than one @vars, then a comma is missing which results into an 'Invalid JSON'. Please add comma to fix this issue.

The @vars of the type ```{{var template_styles |raw}}``` are laso not quick fixed yet. Please also see this.

Thank you.

**Comment by bohdan-harniuk** [comment]
Hi, @RanaMuhammadIrshad!

Thank you for your report. Please, provide the full template that leads to the `Invalid JSON`, fixed be the feature template and expected template. It should contain comments where autogenerated value is incorrect. Thank you.

Regards,

**Comment by bohdan-harniuk** [comment]
Hello @RanaMuhammadIrshad,

I hope you're doing well. It appears that there hasn't been any activity on this issue for over a month, and I wanted to check if it's still relevant or if you've had a chance to address it. If you have any further information or updates to provide, please feel free to reopen the issue, and we'll be happy to assist you.

Best regards,

**Comment by RanaMuhammadIrshad** [comment]
Hello @bohdan-harniuk,

The template that leads to the Invalid JSON is following.

https://github.com/magento/magento2/blob/d9d3d9b40bfdc683ac7c6a26b605481a25e3493e/app/code/Magento/Sales/view/frontend/email/order_new.html#L8-L27

Best regards
