### ISSUE TITLE
No before/after plugin generation?

### ISSUE THREAD

**Issue by peterjaap** [Atwix/phpstorm-plugin-feedback#38]
I can't seem to find a way to generate plugins from any given method in the codebase. Magicento offered this functionality and https://mage2gen.com/ does too, so I thought this plugin would have it too?

**Comment by bohdan-harniuk** [comment]
Hi @peterjaap,

Yes, plugin and mixin generations are planned for the upcoming release.

Regards,

**Comment by bohdan-harniuk** [comment]
Hi @peterjaap ,

We've released plugins generation. You can access it via cmd+g or Generate... + before/after/around plugin by pointing target method. Please, update your plugin version to the latest available.

Regards,
