### ISSUE TITLE
Extend "Compare With Original" Feature

### ISSUE THREAD

**Issue by sprankhub** [Atwix/phpstorm-plugin-feedback#4]
The "Compare Overridden Template with the Original One" feature is awesome! I suggest extending it. I do not know from the top of my head what can be overridden in a theme, but here is a start:

* JS files
* `.html` templates under `web/template`
* layout files (via `override` directory)
* e-mail templates?
* ...?

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub!
Great idea! We'll implement it surely!
Thank you!

**Comment by sprankhub** [comment]
I am not sure if this fits in here. If you think this should be a separate issue, let me know.

If I am looking at a preference, I often want to compare the class with the overridden class. So it would also be nice to have a feature "Compare class with parent" or "Compare preference with original class" or something alike.

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub !

Thank you for your suggestion! It is a great idea. The current issue on the testing stage now, before delivering it. Please, open a separate issue for your suggestion.

Thank you,

**Comment by bohdan-harniuk** [comment]
Hello, @sprankhub!

Please, update your plugin version to the 2023.2.0.
All mentioned here features are implemented in this release.
Feel free to request more features.

Regards,

**Comment by sprankhub** [comment]
Thank you so much!
