### ISSUE TITLE
When using the "Create a new plugin" functionality, only some of the custom modules are shown

### ISSUE THREAD

**Issue by norgeindian** [Atwix/phpstorm-plugin-feedback#52]
How is decided, which modules are shown in the mentioned functionality?
We have about 50 custom modules, all under the same namespace and in the same folder, and only about 10 or 15 can be chosen in the popup.

**Comment by bohdan-harniuk** [comment]
Hello @norgeindian,

To confirm module locations, please clarify: are all of your modules situated within the default Magento source root, which is typically the 'app/code' directory? If not, have any custom source roots been configured?

![Screenshot 2023-12-04 at 14 19 20](https://github.com/Atwix/phpstorm-plugin-feedback/assets/31848341/e4eb7d47-d9fd-470f-8ca0-83c6c3a116cd)

Regards,

**Comment by norgeindian** [comment]
@bohdan-harniuk , we have our custom modules in the `src` directory and this directory is also added to the project:
![image](https://github.com/Atwix/phpstorm-plugin-feedback/assets/11156287/02372b9f-1a83-4901-a317-d029792ab668)

The strange thing is, that some of the modules are present in the dropdown and some are not. Do you see any other reason which could lead to this behaviour?

**Comment by bohdan-harniuk** [comment]
@norgeindian,

Yes, there is a possibility that some modules might not be added to the index. This can only occur if the `registration.php` file contains content that the plugin is unable to parse.

To check whether the target modules are indexed or not, please install the **Index Viewer** module.

![Screenshot 2023-12-05 at 14 17 24](https://github.com/Atwix/phpstorm-plugin-feedback/assets/31848341/757e0bd9-a427-4f1d-b4e1-b42fa7a9da1b)

Once installed, follow these steps to locate the missing module:

1. Open the **Indexes Tool Window** located in the top right corner.

![Screenshot 2023-12-05 at 14 18 26](https://github.com/Atwix/phpstorm-plugin-feedback/assets/31848341/f9039d4f-8809-4d4b-a9db-9c645cc3aa77)

2. Search for the module name

![Screenshot 2023-12-05 at 14 50 40](https://github.com/Atwix/phpstorm-plugin-feedback/assets/31848341/a10efad9-cc86-4a9e-bb35-43f4527b22af)

If the target module is not found, it is likely that the `registration.php` file could not be parsed. In this case, it would be helpful if you could provide the content of the `registration.php` file, replacing the module name with something like XX_YY if necessary.

**But before doing so, you can check if reindexing would help:**

![Screenshot 2023-12-05 at 14 58 54](https://github.com/Atwix/phpstorm-plugin-feedback/assets/31848341/9e85f8f4-847a-48d6-9c58-6fa01669ae36)

Thank you,

**Comment by norgeindian** [comment]
@bohdan-harniuk, thanks for the detailed explanation.
My issue is somehow interesting. The module is properly indexed, but not shown in the dropdown anyway.
Reindexing did not change anything.
What else could I try?

**Comment by bohdan-harniuk** [comment]
@norgeindian, could you please capture a screenshot of the steps involved in creating a plugin? Actually, I am interested only in the screenshot of the action that you choose + dialog where you configure it.

**Comment by norgeindian** [comment]
@bohdan-harniuk , I just checked again and found out, that this action comes from the official Magento plugin and not from your module.
I'm terribly sorry.

**Comment by norgeindian** [comment]
@bohdan-harniuk , thanks for the explanation. That works indeed and there I see all existing modules.
Thanks for your help.
