### ISSUE TITLE
[New feature] Support for factory hints

### ISSUE THREAD

**Issue by m2itester** [Atwix/phpstorm-plugin-feedback#8]
When I use the following code:

```php
use Vendor\Module\Model\CustomFactory;
```

And when I hover my mouse over CustomFactory I get the following message:

`
Undefined class 'CustomFactory'
`

It would be nice if in the case of factory it took into account the files in the `generated` directory

**Comment by bohdan-harniuk** [comment]
Hello, @m2itester!

Sorry for the late response.

It should work as you described out of the box (default PHPStorm functionality).
Check the `var/generated` directory. If CustomFactory class exists here, navigation will work. 
Just do not forget to run: `bin/magento setup:di:compile`.
Please, ping me here, if you need some help with it.

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @m2itester!

Did you try what I suggested? Do you still have that problem?

**Comment by bohdan-harniuk** [comment]
Hi @m2itester,

I’m closing the issue based on my previous response. Feel free to reopen it if you need additional support.

Best regards,
